# Generated by Django 4.2.7 on 2023-12-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.CharField(default='@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='sal',
            field=models.IntegerField(default=50000),
        ),
    ]
