# Generated by Django 4.2.7 on 2023-12-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp_email_alter_emp_sal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
